site_name: Stark
repo_url: https://stark-lou.github.io

theme:
  name: material
  language: zh
  logo: images/assets/avatar.png
  favicon: images/assets/avatar.png

# Disqus
extra:
  disqus: https-stark-lou-github-io-stark

# google_analytics
google_analytics:
  - G-HXH5LVMG2H
  - auto

# repo_url: https://github.com/squidfunk/mkdocs-material